dist: trusty
language: node_js
node_js:
  - '10'
cache: yarn
after_success:
  - cp tooling/deployment-package.json build/package.json
  - cd build && npx now-cd --team auth0-design --alias "master=auth0-cosmos-master.now.sh" --alias "stable=auth0-cosmos.now.sh"
notifications:
  email: false
